# Generated by Django 3.1.5 on 2021-01-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0002_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10)),
                ('preco', models.FloatField()),
                ('alta', models.FloatField()),
                ('baixa', models.FloatField()),
                ('fechAnt', models.FloatField()),
                ('capMerc', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='preco',
            old_name='preço',
            new_name='preco',
        ),
    ]
