# Generated by Django 3.1.5 on 2021-01-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0003_auto_20210105_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salvo',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
