# Generated by Django 3.1.5 on 2021-01-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0004_auto_20210105_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salvo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
