# Generated by Django 3.1.5 on 2021-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0005_auto_20210105_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
