# Generated by Django 3.1.5 on 2021-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0008_auto_20210107_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.FloatField()),
                ('tempo', models.CharField(max_length=10)),
            ],
        ),
    ]
