# Generated by Django 3.1.5 on 2021-01-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0009_tasktime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Perfil',
        ),
    ]
