# Generated by Django 3.1.5 on 2021-01-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0011_auto_20210107_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='limInf',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='limSup',
            field=models.FloatField(blank=True),
        ),
    ]
