# Generated by Django 3.1.5 on 2021-01-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0013_auto_20210107_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.AddField(
            model_name='perfil',
            name='simbolo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cotaAtivos.acao'),
            preserve_default=False,
        ),
    ]
