# Generated by Django 3.1.5 on 2021-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotaAtivos', '0015_auto_20210108_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salvo',
            name='simbolo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
